version: "3.9"

services:
  web:
    build: 
      context: .
      dockerfile: ./docker/DockerFile
    command: bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
